// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("Some Stuff lol");
    println!("cargo:rerun-if-changed=migrations");
}
