use std::process::Command;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=templates");

    //Perform build process for npm
    let output = Command::new("npm")
        .arg("run")
        .arg("build")
        .status().expect("failed to execute process");
    if output.success() {
        println!("cargo:warning= Executing -/- npm run build");
    } else {
        println!("cargo:warning= Failed to execute -/- npm run build");
    }
}
