[package]
name = "axum_super_forms"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-extra = "0.9.3"
mime_guess = "2.0.5"
rust-embed = "8.5.0"
tokio = { version = "1.39.3", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
tower-cookies = "0.10.0"
tower-http = { version = "0.5.0", features = ["fs", "trace"] }


# Enable for Debugging only
# tracing = "0.1.40"
# tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
